name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
        if: ${{ steps.release.outputs.release_created }}
    
      - name: Install and build
        run: |
          pnpm install
          pnpm build
        if: ${{ steps.release.outputs.release_created }}
    
      - name: Publish package to NPM
        run: |
          cd package
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
          npm publish
        if: ${{ steps.release.outputs.release_created }}
