name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
        if: ${{ steps.release.outputs.release_created }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'pnpm'
        if: ${{ steps.release.outputs.release_created }}
    
      - name: Install and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
        if: ${{ steps.release.outputs.release_created }}
